[[redirects]]
  from = "/google_search/*"
  to = "https://anypubmed-2eb75be592db.herokuapp.com/google_search/:splat"
  status = 200
[[redirects]]
  from = "/.well-known/*"
  to = "https://anypubmed-2eb75be592db.herokuapp.com/.well-known/:splat"
  status = 200
[[redirects]]
  from = "/get_full_abstract"
  to = "https://anypubmed-2eb75be592db.herokuapp.com/get_full_abstract"
  status = 200
[[headers]]
  for = "/*.yaml"
  [headers.values]
    Content-Type = "text/yaml"
